server:
  port: 10010 # 网关端口
spring:
  application:
    name: gateway # 服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
      discovery:
        namespace: 0fa8d57a-473d-4edd-bbd9-64fe101067f1 #dev环境
    gateway:
      routes: # 网关路由配置
        - id: zhshl-stock # 路由id，和nacos上服务名一致
          uri: lb://zhshl-stock #和nacos上服务名一致
          predicates:
            - Path=/stock/**
        - id: nacos-demo-order
          uri: lb://nacos-demo-order
          predicates:
            - Path=/**
        - id: user-service # 路由id，自定义，只要唯一即可
            # uri: http://127.0.0.1:8081 # 路由的目标地址 http就是固定地址
          uri: lb://userservice # 路由的目标地址 lb就是负载均衡，后面跟服务名称
          predicates: # 路由断言，也就是判断请求是否符合路由规则的条件
              - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求，就会代理到user